In [2]:
import pandas as pd
import numpy as np

In [3]:
x3_pd = pd.read_csv('X3.csv')
y_pd = pd.read_csv('Y.csv')
#x1_pd['y1'] = y_pd['1']
#x1_pd['y2'] = y_pd['2']
#x1_pd['y3'] = y_pd['3']
#x1_pd['y4'] = y_pd['4']
#x1_pd['y5'] = y_pd['5']

In [6]:
X_train = np.array(x3_pd[[str(i) for i in range(1, 453)]])

In [7]:
x3_pd_test = pd.read_csv('X3_test.csv')

In [8]:
x3_pd_test

,id,1,2,3,4,5,6,7,8,9,...,443,444,445,446,447,448,449,450,451,452
0,0,0.0,0.0,0.0,0.0,0.016949,0.033898,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.050847,0.0,0.0,0.0,0.0
1,1,0.0,0.0,0.0,0.0,0.011236,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.011236,0.0,0.0,0.0,0.0
2,2,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.125000,0.0,0.0,0.0,0.0
3,4,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0
4,7,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4053,8046,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00565,0.073446,0.0,0.0,0.0,0.0
4054,8047,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0
4055,8050,0.0,0.0,0.0,0.0,0.043478,0.612648,0.0,0.003953,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.019763,0.0,0.0,0.0,0.0
4056,8054,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.200000,0.0,0.0,0.0,0.0
4057,8057,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.200000,0.0,0.0,0.0,0.0

In [14]:
X_test = np.array(x3_pd_test[[str(i) for i in range(1, 453)]])

In [16]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
Y_train = np.array(y_pd[['1', '2', '3', '4', '5']])

In [35]:
Y_train

array([[1, 1, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [34]:
with open('3.csv', 'w') as f:
    for i in range(X_test.shape[0]):
        res = np.array([0., 0., 0., 0., 0.])
        w_sum = 0.
        for j in range(X_train.shape[0]):
            w = len((X_train[j] * X_test[i]).nonzero()[0])
            res += w * Y_train[j]
            w_sum += w
        res /= w_sum
        res = [str(val) for val in res]
        f.write(x3_pd_test['id'][i] + ',' + ','.join(res.tolist()) + '\n')

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

In [26]:
len(np.array([1, 0, 1, 0]).nonzero()[0])

2